// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_GW7y1WIEbjkeDDYmmN_S3ILCucp04hg',
    appId: '1:770132290689:web:dfa73c6fcdf71e987e3180',
    messagingSenderId: '770132290689',
    projectId: 'projeto-sti-popcorn',
    authDomain: 'projeto-sti-popcorn.firebaseapp.com',
    storageBucket: 'projeto-sti-popcorn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALEFLXP8OCdKN1OzTL8ruYQ2YgbtTUKk8',
    appId: '1:770132290689:android:2ff3a34c9f8523467e3180',
    messagingSenderId: '770132290689',
    projectId: 'projeto-sti-popcorn',
    storageBucket: 'projeto-sti-popcorn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN0-Vted8874wNmlBmtuzoA-SUrB6P-0w',
    appId: '1:770132290689:ios:9da851d2c1cf7dc17e3180',
    messagingSenderId: '770132290689',
    projectId: 'projeto-sti-popcorn',
    storageBucket: 'projeto-sti-popcorn.appspot.com',
    iosClientId: '770132290689-d375nuqqvhvlu1q0f7gvr7o5ul339uc9.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoSti',
  );
}
